import StyleDictionary from 'style-dictionary';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Get the directory of the current module
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Read font weight values from the generated globals.css
const getGlobalsFontWeights = () => {
  try {
    const globalsPath = path.join(__dirname, 'build/css/globals.css');
    if (fs.existsSync(globalsPath)) {
      const globalsContent = fs.readFileSync(globalsPath, 'utf8');
      const fontWeights = {};
      const regex = /--typography-font-weight-([^:]+):\s*(\d+);/g;
      let match;
      while ((match = regex.exec(globalsContent)) !== null) {
        fontWeights[match[1]] = parseInt(match[2], 10);
      }
      return fontWeights;
    }
  } catch (e) {
    console.warn('Could not read globals.css for font weights');
  }
  return {};
};

// Helper to format token names
const formatTokenName = (name) => {
  return name.toLowerCase()
    .replace(/[․.]/g, '_') // Replace dots with underscores for decimals
    .replace(/\s+/g, '-');
};

// Helper to format reference values to CSS variable names
const formatRefValue = (value) => {
  if (typeof value !== 'string' || !value.startsWith('{')) return value;
  
  let formatted = value
    .replace(/^\{|\}$/g, '')
    .toLowerCase();
  
  // Handle Primitives.Colors
  if (formatted.startsWith('primitives.colors.')) {
    return formatted
      .replace('primitives.colors.', 'color-')
      .replace(/\./g, '-')
      .replace('alpha-alpha-', 'alpha-');
  }
  
  // Handle Primitives.Spacing
  if (formatted.startsWith('primitives.spacing.')) {
    const match = formatted.match(/primitives\.spacing\.([0-9_.]+)/);
    if (match) {
      return `spacing-${match[1].replace(/[.]/g, '_')}`;
    }
  }
  
  // Handle Primitives.Radius
  if (formatted.startsWith('primitives.radius.')) {
    return formatted.replace('primitives.radius.radius-', 'radius-');
  }
  
  // Handle Themes references
  if (formatted.startsWith('themes.')) {
    return formatted.replace('themes.', '').replace(/\./g, '-');
  }
  
  return formatted.replace(/\./g, '-');
};

StyleDictionary.registerFormat({
  name: 'css/tailwind',
  format: ({ dictionary }) => {
    const themeLines = [];
    const processedNames = new Set();

    dictionary.allTokens.forEach((t) => {
      
      let varName = '';
      let actualValue = '';
      
      // Process based on file path
      if (t.filePath === 'tokens/Primitives.json') {
        // Colors - register in @theme to generate utilities (reference globals.css values)
        if (t.name.startsWith('primitives-colors')) {
          const colorName = t.name.replace('primitives-colors-', '').replace('alpha-alpha-', 'alpha-');
          varName = `--color-${colorName}`;
          actualValue = `var(--color-${colorName})`; // Reference from globals.css
        }
        // Spacing - register in @theme to generate utilities (reference globals.css values)
        else if (t.name.startsWith('primitives-spacing')) {
          const nameParts = t.name.replace('primitives-spacing-', '').split('-');
          if (nameParts.length >= 2) {
            const firstNum = nameParts[0];
            const secondNum = nameParts[1];
            let spacingName;
            if (firstNum.match(/^\d+$/) && secondNum === '5') {
              spacingName = `${firstNum}_5`;
            } else if (firstNum.match(/^\d+$/)) {
              spacingName = firstNum;
            }
            if (spacingName) {
              varName = `--spacing-${spacingName}`;
              actualValue = `var(--spacing-${spacingName})`; // Reference from globals.css
            }
          }
        }
        // Radius - register in @theme to generate utilities (reference globals.css values)
        else if (t.name.startsWith('primitives-radius')) {
          const radiusName = t.name.replace('primitives-radius-radius-', '');
          varName = `--radius-${radiusName}`;
          actualValue = `var(--radius-${radiusName})`; // Reference from globals.css
        }
        // Typography - these are mapped differently so we keep them
        else if (t.name.includes('typography')) {
          if (t.name.includes('font-family')) {
            const fontName = t.name.replace('primitives-typography-font-family-font-family-', '');
            varName = `--font-${fontName}`;
            actualValue = `var(--typography-font-family-${fontName})`;
          } else if (t.name.includes('font-weight')) {
            const weightName = t.name.replace('primitives-typography-font-weight-font-weight-', '');
            varName = `--font-weight-${weightName}`;
            // Get the actual numeric value from globals.css which was generated by config.js
            const globalsFontWeights = getGlobalsFontWeights();
            actualValue = globalsFontWeights[weightName] || 400;
          } else if (t.name.includes('text-size')) {
            const sizeName = t.name.replace('primitives-typography-size-text-size-', '');
            varName = `--text-${sizeName}`;
            actualValue = `var(--typography-text-size-${sizeName})`;
          } else if (t.name.includes('line-hight')) {
            const heightName = t.name.replace('primitives-typography-line-hight-line-hight-', '');
            varName = `--leading-${heightName}`;
            actualValue = `var(--typography-line-hight-${heightName})`;
          }
        }
      }
      // Theme tokens - reference the CSS variables from imported theme files
      // ALL color tokens go into --color-* namespace (Tailwind v4 standard)
      else if (t.filePath === 'tokens/Themes.json') {
        let themeName = t.name.toLowerCase().replace(/^themes-/, '');
        
        // Skip global tokens that are aliased from other theme tokens
        if (themeName.startsWith('global-')) return;
        
        // Remove duplicated words
        themeName = themeName.replace(/^background-background-/, 'background-');
        themeName = themeName.replace(/^text-text-/, 'text-');
        themeName = themeName.replace(/^button-button-/, 'button-');
        themeName = themeName.replace(/^border-border-/, 'border-');
        themeName = themeName.replace(/^link-link-/, 'link-');
        themeName = themeName.replace(/^icon-icon-/, 'icon-');
        themeName = themeName.replace(/^alpha-alpha-/, 'alpha-');
        themeName = themeName.replace(/^controls-control-/, 'controls-');
        themeName = themeName.replace(/^table-table-/, 'table-');
        themeName = themeName.replace(/^stepper-stepper-/, 'stepper-');
        themeName = themeName.replace(/^tag-tag-/, 'tag-');
        themeName = themeName.replace(/^tooltip-tooltip-/, 'tooltip-');
        themeName = themeName.replace(/^chip-chip-/, 'chip-');
        themeName = themeName.replace(/^charts-charts-/, 'charts-');
        themeName = themeName.replace(/^progress-bar-progress-bar-/, 'progress-bar-');
        themeName = themeName.replace(/^form-field-/, 'form-');
        themeName = themeName.replace(/^form-text-/, 'form-');
        themeName = themeName.replace(/^form-form-/, 'form-');
        themeName = themeName.replace(/^form-option-/, 'form-');
        themeName = themeName.replace(/^form-datecell-/, 'form-');
        themeName = themeName.replace(/^form-textarea-/, 'form-');
        themeName = themeName.replace(/^global-/, '');
        
        // Store original name for the value reference
        const originalThemeName = themeName;
        
        // ALL color tokens use --color-* namespace (Tailwind v4 standard)
        // This allows using bg-*, text-*, border-* utilities with the same token
        varName = `--color-${themeName}`;
        actualValue = `var(--${originalThemeName})`; // Reference the original theme variable
      }
      
      if (varName && actualValue && !processedNames.has(varName)) {
        processedNames.add(varName);
        themeLines.push(`  ${varName.toLowerCase()}: ${actualValue};`);
      }
    });

    // Dynamically add spacing values from processed tokens
    // These are extracted during token processing above, but some may be missing
    // We scan the processed names and ensure all spacing-* tokens are included
    dictionary.allTokens.forEach((t) => {
      // Handle Primitives spacing tokens (numeric: 0, 0.5, 1, 2, etc.)
      if (t.name.startsWith('primitives-spacing')) {
        const spacingMatch = t.key?.match(/([0-9_.]+)/);
        if (spacingMatch) {
          const spacingName = spacingMatch[1].replace(/[.]/g, '_').replace(/[()pxPX\s,]/g, '');
          if (spacingName && spacingName !== '_' && /\d/.test(spacingName)) {
            const varName = `--spacing-${spacingName}`;
            if (!processedNames.has(varName)) {
              processedNames.add(varName);
              themeLines.push(`  ${varName}: var(--spacing-${spacingName});`);
            }
          }
        }
      }
      
      // Handle ALL semantic spacing tokens from Spacing.json (all categories)
      if (t.filePath === 'tokens/Spacing.json') {
        // Extract the semantic name from token name patterns like:
        // spacing-card-card-lg-padding, spacing-section-section-gap, etc.
        let spacingName = t.name.toLowerCase().replace(/^spacing-/, '');
        
        // Remove duplicated category prefixes
        spacingName = spacingName.replace(/^card-card-/, 'card-');
        spacingName = spacingName.replace(/^section-section-/, 'section-');
        spacingName = spacingName.replace(/^text-text-/, 'text-');
        spacingName = spacingName.replace(/^icon-icon-/, 'icon-');
        spacingName = spacingName.replace(/^button-buttons?-/, 'button-');
        spacingName = spacingName.replace(/^link-links?-/, 'link-');
        spacingName = spacingName.replace(/^control-control-/, 'control-');
        spacingName = spacingName.replace(/^accordion-accordion-/, 'accordion-');
        spacingName = spacingName.replace(/^global-spacing-/, '');
        spacingName = spacingName.replace(/^tooltip-tooltip-/, 'tooltip-');
        spacingName = spacingName.replace(/^form-/, 'form-');
        spacingName = spacingName.replace(/^tab-/, 'tab-');
        spacingName = spacingName.replace(/^table-table-/, 'table-');
        spacingName = spacingName.replace(/^progress-indicator-progress-/, 'progress-');
        spacingName = spacingName.replace(/^pagination-pagination-/, 'pagination-');
        spacingName = spacingName.replace(/^model-modal-/, 'modal-');
        spacingName = spacingName.replace(/^notification-notification-/, 'notification-');
        
        if (spacingName && spacingName !== 'spacing') {
          const varName = `--spacing-${spacingName}`;
          if (!processedNames.has(varName)) {
            processedNames.add(varName);
            themeLines.push(`  ${varName}: var(--spacing-${spacingName});`);
          }
        }
      }
      
      // Handle width tokens from Widths.json
      if (t.name.includes('widths-width-width-')) {
        const widthName = t.name.replace(/.*widths-width-width-/, '');
        if (widthName) {
          const varName = `--width-${widthName}`;
          if (!processedNames.has(varName)) {
            processedNames.add(varName);
            themeLines.push(`  ${varName}: var(--width-${widthName});`);
          }
        }
      }
      
      // Handle radius tokens from Radius.json
      if (t.filePath === 'tokens/Radius.json') {
        let radiusName = t.name.toLowerCase().replace(/^radius-radius-/, '').replace(/^radius-/, '');
        if (radiusName) {
          const varName = `--radius-${radiusName}`;
          if (!processedNames.has(varName)) {
            processedNames.add(varName);
            themeLines.push(`  ${varName}: var(--radius-${radiusName});`);
          }
        }
      }
      
      // Handle container tokens
      if (t.filePath === 'tokens/containers.json') {
        let containerName = t.name.toLowerCase().replace(/^containers-/, '');
        if (containerName) {
          const varName = `--container-${containerName}`;
          if (!processedNames.has(varName)) {
            processedNames.add(varName);
            themeLines.push(`  ${varName}: var(--${containerName});`);
          }
        }
      }
    });

    return `@import 'tailwindcss';
@import './globals.css';
@import './theme-light.css';
@import './theme-dark.css';

@theme {
  /* Reset defaults */
  --color-*: initial;
  --spacing-*: initial;
  --radius-*: initial;
  --font-*: initial;
  --leading-*: initial;
  --text-*: initial;
  --width-*: initial;

${themeLines.join('\n')}
}

`;
  },
});

function getStyleDictionaryConfig() {
  return {
    source: [
      'tokens/Primitives.json',
      'tokens/Spacing.json',
      'tokens/Widths.json',
      'tokens/Radius.json',
      'tokens/Typography.json',
      'tokens/containers.json',
      'tokens/Themes.json',
    ],
    platforms: {
      css: {
        transforms: ['name/kebab'],
        buildPath: 'build/css/',
        files: [
          {
            destination: 'tailwind.css',
            format: 'css/tailwind',
            options: {
              showFileHeader: false,
            },
          },
        ],
      },
    },
  };
}

console.log('\n==============================================');
console.log('\nProcessing: [tailwind]');

const StyleDictionaryConfig = getStyleDictionaryConfig();
const sd = new StyleDictionary(StyleDictionaryConfig);
sd.buildAllPlatforms();

console.log('\nEnd processing');
